login/urls.py
from django.urls import path
from .views import LoginView, LogoutView, CreateAccountView

app_name = 'login'

urlpatterns = [
   path('', LoginView.as_view(), name="login"),
   path('logout/', LogoutView.as_view(), name="logout"),
   path('create/', CreateAccountView.as_view(), name="create"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from store.urls import router


urlpatterns = [
   # path('grappelli/', include('grappelli.urls')),
   path('admin/', admin.site.urls),
   path('other/', include('other.urls')),
   path('login/', include('login.urls')),
   path('', include('store.urls')),
   path('api/', include(router.urls)),
]

store/urls.py
from django.urls import path
from .views import ShopView, CartView, ProductSingleView, CartViewSet, WishListView, WishListAddView, RemoveFromWishList, WishListViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'cart', CartViewSet)
router.register(r'wishlist', WishListViewSet)

app_name = 'store'

urlpatterns = [
    path('', ShopView.as_view(), name='shop'),
    path('cart/', CartView.as_view(), name='cart'),
    path('product/<int:id>/', ProductSingleView.as_view(), name='product'),
    path('wishlist/', WishListView.as_view(), name='wishlist'),
    path('wishlist/add/<int:id>/', WishListAddView.as_view(), name='add_to_wishlist'),
    path('wishlist/remove/<int:id>', RemoveFromWishList.as_view(), name='remove_from_wishlist'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import RegexValidator


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='static/products/', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Discount(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    value = models.IntegerField()
    date_begin = models.DateTimeField()
    date_end = models.DateTimeField()

    def __str__(self):
        return f"{self.product.name}_{self.value}%_{self.date_end}"


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=100, null=True, blank=True)

    phone_regex = RegexValidator(
        regex=r'^\+79\d{9}$',
        message="Phone number must be entered in the format: '+79123456789'."
    )
    phone_number = models.CharField(validators=[phone_regex],
                                    max_length=12,
                                    blank=True,
                                    null=True,
                                    unique=True,
                                    help_text="Формат +79123456789",
                                    )  # максимальная длина 12 символов

    def __str__(self):
        return f"{self.user}"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

store/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponse
from django.db.models import OuterRef, Subquery, F, ExpressionWrapper, DecimalField, Case, When
from django.utils import timezone
from .models import Product, Discount, Cart, Wishlist
from rest_framework import viewsets, response
from rest_framework.permissions import IsAuthenticated
from .serializers import CartSerializer, WishlistSerializer
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User


class ShopView(View):
    def get(self, request):

        # Создание запроса на получения всех действующих не нулевых скидок
        discount_value = Case(When(discount__value__gte=0,
                                   discount__date_begin__lte=timezone.now(),
                                   discount__date_end__gte=timezone.now(),
                                   then=F('discount__value')),
                              default=0,
                              output_field=DecimalField(max_digits=10, decimal_places=2)
                              )

        # Создание запроса на расчёт цены со скидкой
        price_with_discount = ExpressionWrapper(
            F('price') * (100.0 - F('discount_value')) / 100.0,
            output_field=DecimalField(max_digits=10, decimal_places=2)
        )

        products = Product.objects.annotate(
            discount_value=discount_value,
            # Другой способ через запрос в другую таблицу, однако
            # без фильтрации по времени действия скидки
            # discount_value=Subquery(
            #     Discount.objects.filter(product_id=OuterRef('id')).values(
            #         'value')
            # ),
            price_before=F('price'),
            price_after=price_with_discount
        ).values('id', 'name', 'image', 'price_before', 'price_after',
                 'discount_value')
        return render(request, 'store/shop.html', {"data": products})


class CartView(View):
    def get(self, request):
        return render(request, 'store/cart.html')


class ProductSingleView(View):
    def get(self, request, id):
        data = Product.objects.get(id=id)
        return render(request,
                      "store/product-single.html",
                      context={'name': data.name,
                               'description': data.description,
                               'price': data.price,
                               'rating': 5.0,
                               'url': data.image.url,
                               })


class CartViewSet(viewsets.ModelViewSet):
    queryset = Cart.objects.all()
    serializer_class = CartSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        return self.queryset.filter(user=self.request.user)

    def create(self, request, *args, **kwargs):
        ## Можно записать так, для получения товара (проверка что он уже есть в корзине)
        # cart_items = Cart.objects.filter(user=request.user,
        #                                  product__id=request.data.get('product'))
        # Или можно так, так как мы переопределили метод get_queryset
        cart_items = self.get_queryset().filter(product__id=request.data.get('product'))
        # request API передаёт параметры по названиям полей в БД, поэтому ловим product
        if cart_items:  # Если продукт уже есть в корзине
            cart_item = cart_items[0]
            if request.data.get('quantity'):  # Если в запросе передан параметр quantity,
                # то добавляем значение к значению в БД
                cart_item.quantity += int(request.data.get('quantity'))
            else:  # Иначе просто добавляем значение по умолчению 1
                cart_item.quantity += 1
        else:  # Если продукта ещё нет в корзине
            product = get_object_or_404(Product, id=request.data.get('product'))  # Получаем продукт и
            # проверяем что он вообще существует, если его нет то выйдет ошибка 404
            if request.data.get('quantity'):  # Если передаём точное количество продукта, то передаём его
                cart_item = Cart(user=request.user, product=product, quantity=request.data.get('quantity'))
            else:  # Иначе создаём объект по умолчанию (quantity по умолчанию = 1, так прописали в моделях)
                cart_item = Cart(user=request.user, product=product)
        cart_item.save()  # Сохранили объект в БД
        return response.Response({'message': 'Product added to cart'}, status=201)
        # Вернули ответ, что всё прошло успешно

    def update(self, request, *args, **kwargs):
        # Для удобства в kwargs передаётся id строки для изменения в БД, под параметром pk
        cart_item = get_object_or_404(Cart, id=kwargs['pk'])
        if request.data.get('quantity'):
            cart_item.quantity = request.data['quantity']
        if request.data.get('product'):
            product = get_object_or_404(Product, id=request.data['product'])
            cart_item.product = product
        cart_item.save()
        return response.Response({'message': 'Product change to cart'}, status=201)

    def destroy(self, request, *args, **kwargs):
        # В этот раз напишем примерно так как это делает фреймфорк самостоятельно
        cart_item = self.get_queryset().get(id=kwargs['pk'])
        cart_item.delete()
        return response.Response({'message': 'Product delete from cart'}, status=201)


class ProductSingleView(View):
    def get(self, request, id):
        data = Product.objects.get(id=id)
        return render(request,
                      "store/product-single.html",
                      context={'name': data.name,
                               'description': data.description,
                               'price': data.price,
                               'rating': 5.0,
                               'url': data.image.url,
                               })


class WishListView(View):
    def get(self, request):
        if request.user.is_authenticated:
            products = Wishlist.objects.select_related('product').filter(user=self.request.user)
            return render(request, "store/wishlist.html", {"data": products})
        return redirect('login:login')


class WishListAddView(View):
    def get(self, request, id):
        if request.user.is_authenticated:
            item_id = id
            wishlist_items = Wishlist.objects.filter(user=request.user, product__id=item_id)
            if wishlist_items:
                return redirect('store:shop')
            else:
                product = get_object_or_404(Product, id=item_id)
                to_wishlist_item = Wishlist(user=request.user, product=product)
                to_wishlist_item.save()  # Сохранили объект в БД
                return redirect('store:shop')
        return redirect('login:login')


class RemoveFromWishList(View):
    def get(self, request, id):
        wishlist_item = Wishlist.objects.filter(user=request.user, product__id=id)
        wishlist_item.delete()
        return redirect('store:wishlist')


class WishListViewSet(viewsets.ModelViewSet):
    queryset = Wishlist.objects.all()
    serializer_class = WishlistSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        return self.queryset.filter(user=self.request.user)

    def create(self, request, *args, **kwargs):
        wishlist_items = Wishlist.objects.filter(user=request.user, product__id=request.data.get('product'))
        # Или можно так, так как мы переопределили метод get_queryset
        # wl_items = self.get_queryset().filter(product__id=request.data.get('product'))

        # request API передаёт параметры по названиям полей в БД, поэтому ловим product
        if wishlist_items:  # Если продукт уже есть в корзине
            return response.Response({'message': 'Product exists in wishlist'})
        else:  # Если продукта ещё нет в корзине
            product = get_object_or_404(Product, id=request.data.get('product'))  # Получаем продукт и
            # проверяем что он вообще существует, если его нет то выйдет ошибка 404
            wishlist_item = Wishlist(user=request.user, product=product)
            wishlist_item.save()  # Сохранили объект в БД
        return response.Response({'message': 'Product added to wishlist'},
                                 status=201)  # Вернули ответ, что всё прошло успешно

    def destroy(self, request, *args, **kwargs):
        # В этот раз напишем примерно так как это делает фреймфорк самостоятельно
        wishlist_item = self.get_queryset().get(id=kwargs['pk'])
        wishlist_item.delete()
        return response.Response({'message': 'Product deleted from cart'}, status=201)

store/templates/store/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% block header %}
  <head>
    <title>Vegefoods - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'store/css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/animate.css'%}">

    <link rel="stylesheet" href="{% static 'store/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/magnific-popup.css'%}">

    <link rel="stylesheet" href="{% static 'store/css/aos.css'%}">

    <link rel="stylesheet" href="{% static 'store/css/ionicons.min.css'%}">

    <link rel="stylesheet" href="{% static 'store/css/bootstrap-datepicker.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/jquery.timepicker.css'%}">


    <link rel="stylesheet" href="{% static 'store/css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/icomoon.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/style.css'%}">
  </head>
  <body class="goto-here">
		<div class="py-1 bg-primary">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
	    		<div class="col-lg-12 d-block">
		    		<div class="row d-flex">
		    			<div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">+ 1235 2355 98</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">youremail@email.com</span>
					    </div>
					    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
						    <span class="text">3-5 Business days delivery &amp; Free Returns</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="#">Vegefoods</a>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
              	<li class="nav-item"><a class="nav-link" href="{% url 'store:shop' %}">Shop</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'store:cart' %}">Cart</a></li>
                {% if request.user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'store:wishlist' %}">Wishlist</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login:login' %}">Wishlist</a></li>
                {% endif %}
	          <li class="nav-item cta cta-colored"><a href="{% url 'store:cart' %}" class="nav-link"><span class="icon-shopping_cart"></span>[0]</a></li>
            {% if request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link">{{request.user.username}}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'login:logout' %}">Logout</a></li>
                {% if  request.user.is_staff %}
                <li class="nav-item"><a class="nav-link" href="/admin/">To Admin</a></li>
                {% endif %}
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login:login' %}">Login</a></li>
            {% endif %}
	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
        {% endblock %}

        {% block content %}
        {% endblock %}

        {% block footer %}
    <footer class="ftco-footer ftco-section">
      <div class="container">
      	<div class="row">
      		<div class="mouse">
						<a href="#" class="mouse-icon">
							<div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
						</a>
					</div>
      	</div>
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Vegefoods</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Menu</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Shop</a></li>
                <li><a href="#" class="py-2 d-block">About</a></li>
                <li><a href="#" class="py-2 d-block">Journal</a></li>
                <li><a href="#" class="py-2 d-block">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Help</h2>
              <div class="d-flex">
	              <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
	                <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
	                <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
	                <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
	                <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
	              </ul>
	              <ul class="list-unstyled">
	                <li><a href="#" class="py-2 d-block">FAQs</a></li>
	                <li><a href="#" class="py-2 d-block">Contact</a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'store/js/jquery.min.js'%}"></script>
  <script src="{% static 'store/js/jquery-migrate-3.0.1.min.js'%}"></script>
  <script src="{% static 'store/js/popper.min.js'%}"></script>
  <script src="{% static 'store/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'store/js/jquery.easing.1.3.js'%}"></script>
  <script src="{% static 'store/js/jquery.waypoints.min.js'%}"></script>
  <script src="{% static 'store/js/jquery.stellar.min.js'%}"></script>
  <script src="{% static 'store/js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'store/js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{% static 'store/js/aos.js'%}"></script>
  <script src="{% static 'store/js/jquery.animateNumber.min.js'%}"></script>
  <script src="{% static 'store/js/bootstrap-datepicker.js'%}"></script>
  <script src="{% static 'store/js/scrollax.min.js'%}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'store/js/google-map.js'%}"></script>
  <script src="{% static 'store/js/main.js'%}"></script>
  {% endblock %}
  {% block scripts %}
  {% endblock %}

  </body>
</html>

store/templates/store/shop.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'store/images/bg_1.jpg'%});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Products</span></p>
            <h1 class="mb-0 bread">Products</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10 mb-5 text-center">
    				<ul class="product-category">
    					<li><a href="#" class="active">All</a></li>
    					<li><a href="#">Vegetables</a></li>
    					<li><a href="#">Fruits</a></li>
    					<li><a href="#">Juice</a></li>
    					<li><a href="#">Dried</a></li>
    				</ul>
    			</div>
    		</div>
    		<div class="row">
{% for product in data %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="product">
    					<a href="{% url 'store:product' product.id %}" class="img-prod"><img class="img-fluid" src="/{{ product.image }}" alt="Colorlib Template">
							{% if product.discount_value %}
    						<span class="status">{{product.discount_value}}%</span>
							{% endif %}
    						<div class="overlay"></div>
    					</a>
    					<div class="text py-3 pb-4 px-3 text-center">
    						<h3><a href="#">{{product.name}}</a></h3>
    						<div class="d-flex">
    							<div class="pricing">
									{% if product.discount_value %}
		    						<p class="price"><span class="mr-2 price-dc">${{product.price_before}}</span><span class="price-sale">${{product.price_after}}</span></p>
									{% else %}
									<p class="price"><span>${{product.price_before}}</span></p>
									{% endif %}
		    					</div>
	    					</div>
	    					<div class="bottom-area d-flex px-3">
	    						<div class="m-auto d-flex">
	    							<a href="#" class="add-to-cart d-flex justify-content-center align-items-center text-center">
	    								<span><i class="ion-ios-menu"></i></span>
	    							</a>
	    							<a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1">
	    								<span><i class="ion-ios-cart"></i></span>
	    							</a>
	    							<a href="{% url 'store:add_to_wishlist' product.id %}" class="heart d-flex justify-content-center align-items-center ">
	    								<span><i class="ion-ios-heart"></i></span>
	    							</a>
    							</div>
    						</div>
    					</div>
    				</div>
    			</div>
{% endfor %}
    		</div>
    		<div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
    	</div>
    </section>

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

store/templates/store/wishlist.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'store/images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Wishlist</span></p>
            <h1 class="mb-0 bread">My Wishlist</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>Product List</th>
						        <th>&nbsp;</th>
						        <th>Price</th>
						      </tr>
						    </thead>
						    <tbody>
						      {% for item in data %}<!-- Начало цикла-->
                                <tr class="text-center">
                                    <!-- Опционально! Реализовать, что при нажатии на крестик удаляется товар из Wishlist,
                                    соответственно пишите ссылку на обработчик. Обработчик принимает параметр id товара
                                    который он должен удалить из БД, удаляет его и возвращает перенаправление (redirect)
                                    на обработчик wishlist, который показывает страницу wishlist-->
                                    <td class="product-remove"><a href="{% url 'store:remove_from_wishlist' item.product.id %}"><span class="ion-ios-close"></span></a></td>
                                    <!-- При нажатии на картинку (подставить из БД) должен быть переход на соответствующий товар ссылку прописать в href-->
                                    <td class="image-prod"><a href="{% url 'store:product' item.product.id %}"><div class="img" style="background-image:url(/{{ item.product.image }});"></div></a></td>

                                    <td class="product-name">
                                        <h3>{{item.product.name}}</h3><!-- Название из БД-->
                                        <p>{{item.product.description}}</p><!-- Описание из БД-->
                                    </td>

                                    <td class="price">${{item.product.price}}</td><!-- Стоимость из БД-->

                                  </tr>
                              {% endfor %}<!-- Конец цикла-->
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
			</div>
		</section>

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
{% endblock %}