login/urls.py
from django.urls import path
from .views import LoginView, LogoutView, CreateAccountView

app_name = 'login'

urlpatterns = [
   path('', LoginView.as_view(), name="login"),
   path('logout/', LogoutView.as_view(), name="logout"),
   path('create/', CreateAccountView.as_view(), name="create"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from store.urls import router


urlpatterns = [
   # path('grappelli/', include('grappelli.urls')),
   path('admin/', admin.site.urls),
   path('other/', include('other.urls')),
   path('login/', include('login.urls')),
   path('', include('store.urls')),
   path('api/', include(router.urls)),
]

login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.forms import UsernameField
from django.forms import EmailField


def validate_user(value):
    if not User.objects.filter(username=value).exists():
        raise ValidationError('User Does Not Exist')
    return value


user = UsernameField(validators=[validate_user])


def validate_email(value):
   if User.objects.filter(email=value).exists():
       raise ValidationError('Email Already Exists')
   return value


email = EmailField(validators=[validate_email])


class CustomUserCreationForm(UserCreationForm):
    email = EmailField()

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError('Email Already Exists')

        return email

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        field_classes = {"username": UsernameField}

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.views import View
from django.http import JsonResponse
from .forms import CustomUserCreationForm


class LoginView(View):
    def get(self, request):
        return render(request, 'login/index.html')

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('store:shop')
        return render(request, "login/index.html",
                      context={'errors': form.errors})


class LogoutView(View):
   def get(self, request):
       if request.user.is_authenticated:
           logout(request)
       return redirect('store:shop')


class CreateAccountView(View):
   def get(self, request):
       return render(request, "login/create_account.html")

   def post(self, request):
       form = CustomUserCreationForm(data=request.POST)
       if form.is_valid():
           username = form.cleaned_data.get('username')
           email = form.cleaned_data.get('email')
           password = form.cleaned_data.get('password1')
           user = User.objects.create_user(username=username, email=email, password=password)
           user.save()
           login(request, user, backend='django.contrib.auth.backends.ModelBackend')
           return redirect('store:shop')
       return render(request, "login/create_account.html",
                     context={'errors': form.errors})

login/templates/login/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href='{% static "login/images/icons/favicon.ico" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/vendor/bootstrap/css/bootstrap.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/vendor/animate/animate.css" %}'>
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href='{% static "login/vendor/css-hamburgers/hamburgers.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/vendor/select2/select2.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/css/util.css" %}'>
	<link rel="stylesheet" type="text/css" href='{% static "login/css/main.css" %}'>
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src='{% static "login/images/img-01.png" %}' alt="IMG">
				</div>
                {% block content %}
                {% endblock %}
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src='{% static "login/vendor/jquery/jquery-3.2.1.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "login/vendor/bootstrap/js/popper.js" %}'></script>
	<script src='{% static "login/vendor/bootstrap/js/bootstrap.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "login/vendor/select2/select2.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "login/vendor/tilt/tilt.jquery.min.js" %}'></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src='{% static "login/js/main.js" %}'></script>

</body>
</html>

login/templates/login/create_account.html
{% extends 'login/base.html' %}
{% load static %}
{% block content %}
				<form action="." method="post" class="login100-form validate-form">
					{% csrf_token %}
					<span class="login100-form-title">
						Create New Member
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user-o" aria-hidden="true"></i>
						</span>
					</div>
					{% if errors.username%}
					<span class="txt1">
						{{errors.username}}
					</span>
					{% endif %}
                    <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                        <input class="input100" type="text" name="email" placeholder="Email">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>
					{% if errors.email%}
					<span class="txt1">
						{{errors.email}}
					</span>
					{% endif %}
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password1" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					{% if errors.password1%}
					<span class="txt1">
						{{errors.password1}}
					</span>
					{% endif %}
                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password2" placeholder="Repeat password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					{% if errors.password2%}
					<span class="txt1">
						{{errors.password2}}
					</span>
					{% endif %}
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Create
						</button>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'login:login' %}">
							Already have an account?
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
{% endblock %}

login/templates/login/index.html
{% extends 'login/base.html' %}
{% load static %}
{% block content %}
				<form action="." method="post" class="login100-form validate-form">
					{% csrf_token %}
					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user-o" aria-hidden="true"></i>
						</span>
					</div>
					{% if errors.username%}
					<span class="txt1">
						{{errors.username}}
					</span>
					{% endif %}
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href='{% static "login/#" %}'>
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href='{% url "login:create" %}'>
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
{% endblock %}